# Site settings
title: PaoloBattistella.it | Web Artisan
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paolobattistella.it" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: samarsault/plainwhite-jekyll
theme: plainwhite

plainwhite:
  name: Paolo Battistella
  tagline: Web Artisan

  html_lang: "en"
  date_format: "%-d %b %Y"
  dark_mode: true

  social_links:
    github: paolobattistella
    linkedIn: in/paolobattistella

  portfolio_image: "assets/img/me.jpeg"

  sitemap: true

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
